// Generated by scripts/update-links.mjs.
// Links listed here are hidden from the end-user UI until the next successful check.
export const BLOCKED_LINK_URLS: string[] = [
  "http://kuopionkaupunginteatteri.fi/",
  "https://haapavesi.fi/",
  "https://piki.verkkokirjasto.fi/",
  "https://www.aland.fi/",
  "https://www.digihakemisto.net",
  "https://www.gutenberg.org",
  "https://www.lapinlahti.fi/",
  "https://www.vapaaehtoistyö.fi",
];
