// Generated by scripts/update-links.mjs.
export const LINK_STATS = {
  totalLinks: 1518,
  visibleLinks: 1314,
  hiddenLinks: 204,
  phoneLinks: 88,
  categoryCount: 40,
  sections: {
    "Alueelliset puhelinnumerot": 42,
    "Alueelliset uutislähteet": 16,
    "Hyvinvointialueet": 44,
    "Kuntien kieliversiot": 235,
    "Kuntien verkkosivut": 297,
    "Lehdet": 120,
    "Paikallinen ohjattu liikunta": 152,
    "Paikalliset erikoislinkit": 163,
    "Paikalliset urheiluseurat": 41,
    "Palvelukategoriat": 379,
    "Sovelluksen omat linkit": 6,
    "Uutisvirrat": 23,
  } as Record<string, number>,
} as const;
