// Generated by scripts/update-links.mjs.
export const LINK_STATS = {
  totalLinks: 1018,
  visibleLinks: 1018,
  hiddenLinks: 0,
  categoryCount: 34,
  sections: {
    "Alueelliset uutislähteet": 16,
    "Hyvinvointialueet": 44,
    "Kuntien kieliversiot": 235,
    "Kuntien verkkosivut": 297,
    "Lehdet": 108,
    "Paikalliset erikoislinkit": 24,
    "Palvelukategoriat": 288,
    "Sovelluksen omat linkit": 6,
  } as Record<string, number>,
} as const;
