// Generated by scripts/update-links.mjs.
// Links listed here are hidden from the end-user UI until the next successful check.
export const BLOCKED_LINK_URLS: string[] = [
  "https://topikki.fi/",
  "https://www.kotka.fi/",
  "https://www.kotka.fi/en/",
  "https://www.kotka.fi/ru/",
  "https://www.kotka.fi/vapaa-aika/liikunta/liikuntaryhmat/",
];
