// Generated by scripts/update-links.mjs.
// Links listed here are hidden from the end-user UI until the next successful check.
export const BLOCKED_LINK_URLS: string[] = [
  "https://fibo.fi/",
  "https://l-tanssi.fi/",
  "https://meneva.fi",
  "https://myrskyla.fi/",
  "https://myrskyla.fi/palvelut/hyvinvointipalvelut/liikuntapalvelut/ohjatut-liikuntaryhmat/",
  "https://susannaleinonen.com",
  "https://topikki.fi/",
  "https://umohelsinki.fi/",
  "https://www.susel.fi/",
  "https://www.susel.fi/susel/seuratanssi/",
  "https://www.tapiolanhonka.fi/",
  "https://www.teatterivantaa.fi/",
];
