// Generated by scripts/update-links.mjs.
export const LINK_STATS = {
  totalLinks: 2046,
  visibleLinks: 1898,
  hiddenLinks: 148,
  phoneLinks: 88,
  categoryCount: 40,
  sections: {
    "Alueelliset puhelinnumerot": 42,
    "Alueelliset uutislähteet": 50,
    "Hyvinvointialueet": 46,
    "Kuntien kieliversiot": 235,
    "Kuntien verkkosivut": 308,
    "Lehdet": 119,
    "Paikallinen ohjattu liikunta": 152,
    "Paikalliset erikoislinkit": 296,
    "Paikalliset senioripalvelut": 123,
    "Paikalliset urheiluseurat": 45,
    "Palvelukategoriat": 379,
    "Sovelluksen omat linkit": 6,
    "Uutisvirrat": 245,
  } as Record<string, number>,
} as const;
