// Generated by scripts/update-links.mjs.
export const LOCAL_LINK_STATS = {
  municipalities: 297,
  municipalityLanguageVersions: 235,
  wellbeingAreas: 44,
  municipalityServicePages: 9,
  localTransport: 13,
  localServiceTransport: 137,
  localLibraries: 7,
  localNewspapers: 120,
  localNewsFeeds: 23,
  localSportsClubs: 41,
  localExerciseLinks: 152,
  localKelaTaxiPhones: 42,
} as const;
