import type { RegionalProvider } from './communityLinks';

export const KELA_TAXI_SOURCE_URL = 'https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868';

// Generated from Kela PDF: Kela-taksin tilausnumerot maakunnittain 1.1.2022.
export const KELA_TAXI_PROVIDERS: RegionalProvider[] = [
  {
    name: "Kela-taksi: DRide Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-1",
    group: 'Kela-taksi',
    phone: "0800 101 010",
    phoneUrl: 'tel:0800101010',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Heinävesi",
      "Ilomantsi",
      "Joensuu",
      "Juuka",
      "Kitee",
      "Kontiolahti",
      "Lieksa",
      "Liperi",
      "Nurmes",
      "Outokumpu",
      "Polvijärvi",
      "Rääkkylä",
      "Tohmajärvi",
    ],
  },
  {
    name: "Kela-taksi: DRide Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-2",
    group: 'Kela-taksi',
    phone: "0800 415 700",
    phoneUrl: 'tel:0800415700',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Enonkoski",
      "Hirvensalmi",
      "Juva",
      "Kangasniemi",
      "Mikkeli",
      "Mäntyharju",
      "Pieksämäki",
      "Puumala",
      "Rantasalmi",
      "Savonlinna",
      "Sulkava",
    ],
  },
  {
    name: "Kela-taksi: DRide Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-3",
    group: 'Kela-taksi',
    phone: "0800 415 750",
    phoneUrl: 'tel:0800415750',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Hamina",
      "Kotka",
      "Kouvola",
      "Miehikkälä",
      "Pyhtää",
      "Virolahti",
    ],
  },
  {
    name: "Kela-taksi: Joensuun Taksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-4",
    group: 'Kela-taksi',
    phone: "0800 102 000",
    phoneUrl: 'tel:0800102000',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Iisalmi",
      "Joroinen",
      "Kaavi",
      "Keitele",
      "Kiuruvesi",
      "Kuopio",
      "Lapinlahti",
      "Leppävirta",
      "Pielavesi",
      "Rautalampi",
      "Rautavaara",
      "Siilinjärvi",
      "Sonkajärvi",
      "Suonenjoki",
      "Tervo",
      "Tuusniemi",
      "Varkaus",
      "Vesanto",
      "Vieremä",
    ],
  },
  {
    name: "Kela-taksi: Kainuun Taksivälitys Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-5",
    group: 'Kela-taksi',
    phone: "0800 933 99",
    phoneUrl: 'tel:080093399',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Hyrynsalmi",
      "Kajaani",
      "Kuhmo",
      "Paltamo",
      "Puolanka",
      "Ristijärvi",
      "Sotkamo",
      "Suomussalmi",
    ],
  },
  {
    name: "Kela-taksi: Keskustaksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-6",
    group: 'Kela-taksi',
    phone: "0800 924 40",
    phoneUrl: 'tel:080092440',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Alajärvi",
      "Alavus",
      "Evijärvi",
      "Ilmajoki",
      "Isojoki",
      "Isokyrö",
      "Karijoki",
      "Kauhajoki",
      "Kauhava",
      "Kuortane",
      "Kurikka",
      "Lappajärvi",
      "Lapua",
      "Seinäjoki",
      "Soini",
      "Teuva",
      "Vimpeli",
      "Ähtäri",
    ],
  },
  {
    name: "Kela-taksi: Keskustaksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-7",
    group: 'Kela-taksi',
    phone: "0800 924 42",
    phoneUrl: 'tel:080092442',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Eura",
      "Eurajoki",
      "Harjavalta",
      "Huittinen",
      "Jämijärvi",
      "Kankaanpää",
      "Karvia",
      "Kokemäki",
      "Merikarvia",
      "Nakkila",
      "Pomarkku",
      "Pori",
      "Rauma",
      "Siikainen",
      "Säkylä",
      "Ulvila",
    ],
  },
  {
    name: "Kela-taksi: Keskustaksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-8",
    group: 'Kela-taksi',
    phone: "0800 924 44",
    phoneUrl: 'tel:080092444',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Kaskinen",
      "Korsnäs",
      "Kristiinankaupunki",
      "Kruunupyy",
      "Laihia",
      "Luoto",
      "Maalahti",
      "Mustasaari",
      "Närpiö",
      "Pedersören kunta",
      "Pietarsaari",
      "Uusikaarlepyy",
      "Vaasa",
      "Vöyri",
    ],
  },
  {
    name: "Kela-taksi: Lahden Aluetaksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-9",
    group: 'Kela-taksi',
    phone: "0800 301 23",
    phoneUrl: 'tel:080030123',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Asikkala",
      "Hartola",
      "Heinola",
      "Hollola",
      "Iitti",
      "Kärkölä",
      "Lahti",
      "Orimattila",
      "Padasjoki",
      "Sysmä",
    ],
  },
  {
    name: "Kela-taksi: Menevä Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-10",
    group: 'Kela-taksi',
    phone: "0800 021 80",
    phoneUrl: 'tel:080002180',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Aura",
      "Kaarina",
      "Kemiönsaari",
      "Koski Tl",
      "Kustavi",
      "Laitila",
      "Lieto",
      "Loimaa",
      "Marttila",
      "Masku",
      "Mynämäki",
      "Naantali",
      "Nousiainen",
      "Oripää",
      "Paimio",
      "Parainen",
      "Pyhäranta",
      "Pöytyä",
      "Raisio",
      "Rusko",
      "Salo",
      "Sauvo",
      "Somero",
      "Taivassalo",
      "Turku",
      "Uusikaupunki",
      "Vehmaa",
    ],
  },
  {
    name: "Kela-taksi: Menevä Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-11",
    group: 'Kela-taksi',
    phone: "0800 021 83",
    phoneUrl: 'tel:080002183',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Hankasalmi",
      "Joutsa",
      "Jyväskylä",
      "Jämsä",
      "Kannonkoski",
      "Karstula",
      "Keuruu",
      "Kinnula",
      "Kivijärvi",
      "Konnevesi",
      "Kyyjärvi",
      "Laukaa",
      "Luhanka",
      "Multia",
      "Muurame",
      "Petäjävesi",
      "Pihtipudas",
      "Saarijärvi",
      "Toivakka",
      "Uurainen",
      "Viitasaari",
      "Äänekoski",
    ],
  },
  {
    name: "Kela-taksi: Menevä Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-12",
    group: 'Kela-taksi',
    phone: "0800 021 85",
    phoneUrl: 'tel:080002185',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Heinävesi",
      "Ilomantsi",
      "Joensuu",
      "Juuka",
      "Kitee",
      "Kontiolahti",
      "Lieksa",
      "Liperi",
      "Nurmes",
      "Outokumpu",
      "Polvijärvi",
      "Rääkkylä",
      "Tohmajärvi",
    ],
  },
  {
    name: "Kela-taksi: Menevä Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-13",
    group: 'Kela-taksi',
    phone: "0800 021 89",
    phoneUrl: 'tel:080002189',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Hyrynsalmi",
      "Kajaani",
      "Kuhmo",
      "Paltamo",
      "Puolanka",
      "Ristijärvi",
      "Sotkamo",
      "Suomussalmi",
    ],
  },
  {
    name: "Kela-taksi: Pohjois-Suomen Taksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-14",
    group: 'Kela-taksi',
    phone: "0800 933 77",
    phoneUrl: 'tel:080093377',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Alavieska",
      "Haapajärvi",
      "Haapavesi",
      "Hailuoto",
      "Halsua",
      "Ii",
      "Kalajoki",
      "Kannus",
      "Kaustinen",
      "Kempele",
      "Kokkola",
      "Kuusamo",
      "Kärsämäki",
      "Lestijärvi",
      "Liminka",
      "Lumijoki",
      "Merijärvi",
      "Muhos",
      "Nivala",
      "Oulainen",
      "Oulu",
      "Perho",
      "Pudasjärvi",
      "Pyhäjoki",
      "Pyhäjärvi",
      "Pyhäntä",
      "Raahe",
      "Reisjärvi",
      "Sievi",
      "Siikajoki",
      "Siikalatva",
      "Taivalkoski",
      "Toholampi",
      "Tyrnävä",
      "Utajärvi",
      "Vaala",
      "Veteli",
      "Ylivieska",
    ],
  },
  {
    name: "Kela-taksi: Suomen Lähilogistiikka Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-15",
    group: 'Kela-taksi',
    phone: "0800 051 50",
    phoneUrl: 'tel:080005150',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Askola",
      "Espoo",
      "Hanko",
      "Helsinki",
      "Hyvinkää",
      "Inkoo",
      "Järvenpää",
      "Karkkila",
      "Kauniainen",
      "Kerava",
      "Kirkkonummi",
      "Lapinjärvi",
      "Lohja",
      "Loviisa",
      "Myrskylä",
      "Mäntsälä",
      "Nurmijärvi",
      "Pornainen",
      "Porvoo",
      "Pukkila",
      "Raasepori",
      "Sipoo",
      "Siuntio",
      "Tuusula",
      "Vantaa",
      "Vihti",
    ],
  },
  {
    name: "Kela-taksi: Suomen Lähilogistiikka Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-16",
    group: 'Kela-taksi',
    phone: "0800 051 54",
    phoneUrl: 'tel:080005154',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Enontekiö",
      "Inari",
      "Kemi",
      "Kemijärvi",
      "Keminmaa",
      "Kittilä",
      "Kolari",
      "Muonio",
      "Pelkosenniemi",
      "Pello",
      "Posio",
      "Ranua",
      "Rovaniemi",
      "Salla",
      "Savukoski",
      "Simo",
      "Sodankylä",
      "Tervola",
      "Tornio",
      "Utsjoki",
      "Ylitornio",
    ],
  },
  {
    name: "Kela-taksi: Suomen Lähilogistiikka Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-17",
    group: 'Kela-taksi',
    phone: "0800 051 57",
    phoneUrl: 'tel:080005157',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Forssa",
      "Hattula",
      "Hausjärvi",
      "Humppila",
      "Hämeenlinna",
      "Janakkala",
      "Jokioinen",
      "Loppi",
      "Riihimäki",
      "Tammela",
      "Ypäjä",
    ],
  },
  {
    name: "Kela-taksi: Suomen Lähilogistiikka Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-18",
    group: 'Kela-taksi',
    phone: "0800 051 60",
    phoneUrl: 'tel:080005160',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Asikkala",
      "Hartola",
      "Heinola",
      "Hollola",
      "Iitti",
      "Kärkölä",
      "Lahti",
      "Orimattila",
      "Padasjoki",
      "Sysmä",
    ],
  },
  {
    name: "Kela-taksi: Suomen Lähilogistiikka Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-19",
    group: 'Kela-taksi',
    phone: "0800 051 63",
    phoneUrl: 'tel:080005163',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Hamina",
      "Kotka",
      "Kouvola",
      "Miehikkälä",
      "Pyhtää",
      "Virolahti",
    ],
  },
  {
    name: "Kela-taksi: Taksi Helsinki Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-20",
    group: 'Kela-taksi',
    phone: "0800 414 600",
    phoneUrl: 'tel:0800414600',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Askola",
      "Espoo",
      "Hanko",
      "Helsinki",
      "Hyvinkää",
      "Inkoo",
      "Järvenpää",
      "Karkkila",
      "Kauniainen",
      "Kerava",
      "Kirkkonummi",
      "Lapinjärvi",
      "Lohja",
      "Loviisa",
      "Myrskylä",
      "Mäntsälä",
      "Nurmijärvi",
      "Pornainen",
      "Porvoo",
      "Pukkila",
      "Raasepori",
      "Sipoo",
      "Siuntio",
      "Tuusula",
      "Vantaa",
      "Vihti",
    ],
  },
  {
    name: "Kela-taksi: Taksi Helsinki Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-21",
    group: 'Kela-taksi',
    phone: "0800 414 603",
    phoneUrl: 'tel:0800414603',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Aura",
      "Kaarina",
      "Kemiönsaari",
      "Koski Tl",
      "Kustavi",
      "Laitila",
      "Lieto",
      "Loimaa",
      "Marttila",
      "Masku",
      "Mynämäki",
      "Naantali",
      "Nousiainen",
      "Oripää",
      "Paimio",
      "Parainen",
      "Pyhäranta",
      "Pöytyä",
      "Raisio",
      "Rusko",
      "Salo",
      "Sauvo",
      "Somero",
      "Taivassalo",
      "Turku",
      "Uusikaupunki",
      "Vehmaa",
    ],
  },
  {
    name: "Kela-taksi: Taksi Helsinki Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-22",
    group: 'Kela-taksi',
    phone: "0800 414 606",
    phoneUrl: 'tel:0800414606',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Akaa",
      "Hämeenkyrö",
      "Ikaalinen",
      "Juupajoki",
      "Kangasala",
      "Kihniö",
      "Kuhmoinen",
      "Lempäälä",
      "Mänttä-Vilppula",
      "Nokia",
      "Orivesi",
      "Parkano",
      "Pirkkala",
      "Punkalaidun",
      "Pälkäne",
      "Ruovesi",
      "Sastamala",
      "Tampere",
      "Urjala",
      "Valkeakoski",
      "Vesilahti",
      "Virrat",
      "Ylöjärvi",
    ],
  },
  {
    name: "Kela-taksi: Taksi Helsinki Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-23",
    group: 'Kela-taksi',
    phone: "0800 414 608",
    phoneUrl: 'tel:0800414608',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Hankasalmi",
      "Joutsa",
      "Jyväskylä",
      "Jämsä",
      "Kannonkoski",
      "Karstula",
      "Keuruu",
      "Kinnula",
      "Kivijärvi",
      "Konnevesi",
      "Kyyjärvi",
      "Laukaa",
      "Luhanka",
      "Multia",
      "Muurame",
      "Petäjävesi",
      "Pihtipudas",
      "Saarijärvi",
      "Toivakka",
      "Uurainen",
      "Viitasaari",
      "Äänekoski",
    ],
  },
  {
    name: "Kela-taksi: Taksi Helsinki Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-24",
    group: 'Kela-taksi',
    phone: "0800 414 610",
    phoneUrl: 'tel:0800414610',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Enontekiö",
      "Inari",
      "Kemi",
      "Kemijärvi",
      "Keminmaa",
      "Kittilä",
      "Kolari",
      "Muonio",
      "Pelkosenniemi",
      "Pello",
      "Posio",
      "Ranua",
      "Rovaniemi",
      "Salla",
      "Savukoski",
      "Simo",
      "Sodankylä",
      "Tervola",
      "Tornio",
      "Utsjoki",
      "Ylitornio",
    ],
  },
  {
    name: "Kela-taksi: Taksi Helsinki Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-25",
    group: 'Kela-taksi',
    phone: "0800 414 612",
    phoneUrl: 'tel:0800414612',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Eura",
      "Eurajoki",
      "Harjavalta",
      "Huittinen",
      "Jämijärvi",
      "Kankaanpää",
      "Karvia",
      "Kokemäki",
      "Merikarvia",
      "Nakkila",
      "Pomarkku",
      "Pori",
      "Rauma",
      "Siikainen",
      "Säkylä",
      "Ulvila",
    ],
  },
  {
    name: "Kela-taksi: Taksi Helsinki Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-26",
    group: 'Kela-taksi',
    phone: "0800 414 614",
    phoneUrl: 'tel:0800414614',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Iisalmi",
      "Joroinen",
      "Kaavi",
      "Keitele",
      "Kiuruvesi",
      "Kuopio",
      "Lapinlahti",
      "Leppävirta",
      "Pielavesi",
      "Rautalampi",
      "Rautavaara",
      "Siilinjärvi",
      "Sonkajärvi",
      "Suonenjoki",
      "Tervo",
      "Tuusniemi",
      "Varkaus",
      "Vesanto",
      "Vieremä",
    ],
  },
  {
    name: "Kela-taksi: Taksi Helsinki Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-27",
    group: 'Kela-taksi',
    phone: "0800 414 616",
    phoneUrl: 'tel:0800414616',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Forssa",
      "Hattula",
      "Hausjärvi",
      "Humppila",
      "Hämeenlinna",
      "Janakkala",
      "Jokioinen",
      "Loppi",
      "Riihimäki",
      "Tammela",
      "Ypäjä",
    ],
  },
  {
    name: "Kela-taksi: Taksi Päijänne Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-28",
    group: 'Kela-taksi',
    phone: "0800 021 87",
    phoneUrl: 'tel:080002187',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Imatra",
      "Lappeenranta",
      "Lemi",
      "Luumäki",
      "Parikkala",
      "Rautjärvi",
      "Ruokolahti",
      "Savitaipale",
      "Taipalsaari",
    ],
  },
  {
    name: "Kela-taksi: Taksi Saimaa Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-29",
    group: 'Kela-taksi',
    phone: "0800 555 123",
    phoneUrl: 'tel:0800555123',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Imatra",
      "Lappeenranta",
      "Lemi",
      "Luumäki",
      "Parikkala",
      "Rautjärvi",
      "Ruokolahti",
      "Savitaipale",
      "Taipalsaari",
    ],
  },
  {
    name: "Kela-taksi: Tampereen Aluetaksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-30",
    group: 'Kela-taksi',
    phone: "0800 306 600",
    phoneUrl: 'tel:0800306600',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Enonkoski",
      "Hirvensalmi",
      "Juva",
      "Kangasniemi",
      "Mikkeli",
      "Mäntyharju",
      "Pieksämäki",
      "Puumala",
      "Rantasalmi",
      "Savonlinna",
      "Sulkava",
    ],
  },
  {
    name: "Kela-taksi: Tampereen Aluetaksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-31",
    group: 'Kela-taksi',
    phone: "0800 415 710",
    phoneUrl: 'tel:0800415710',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Akaa",
      "Hämeenkyrö",
      "Ikaalinen",
      "Juupajoki",
      "Kangasala",
      "Kihniö",
      "Kuhmoinen",
      "Lempäälä",
      "Mänttä-Vilppula",
      "Nokia",
      "Orivesi",
      "Parkano",
      "Pirkkala",
      "Punkalaidun",
      "Pälkäne",
      "Ruovesi",
      "Sastamala",
      "Tampere",
      "Urjala",
      "Valkeakoski",
      "Vesilahti",
      "Virrat",
      "Ylöjärvi",
    ],
  },
  {
    name: "Kela-taksi: Tampereen Aluetaksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-32",
    group: 'Kela-taksi',
    phone: "0800 415 720",
    phoneUrl: 'tel:0800415720',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Alavieska",
      "Haapajärvi",
      "Haapavesi",
      "Hailuoto",
      "Halsua",
      "Ii",
      "Kalajoki",
      "Kannus",
      "Kaustinen",
      "Kempele",
      "Kokkola",
      "Kuusamo",
      "Kärsämäki",
      "Lestijärvi",
      "Liminka",
      "Lumijoki",
      "Merijärvi",
      "Muhos",
      "Nivala",
      "Oulainen",
      "Oulu",
      "Perho",
      "Pudasjärvi",
      "Pyhäjoki",
      "Pyhäjärvi",
      "Pyhäntä",
      "Raahe",
      "Reisjärvi",
      "Sievi",
      "Siikajoki",
      "Siikalatva",
      "Taivalkoski",
      "Toholampi",
      "Tyrnävä",
      "Utajärvi",
      "Vaala",
      "Veteli",
      "Ylivieska",
    ],
  },
  {
    name: "Kela-taksi: Vaasan Ulataksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-33",
    group: 'Kela-taksi',
    phone: "0800 500 100",
    phoneUrl: 'tel:0800500100',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Alajärvi",
      "Alavus",
      "Evijärvi",
      "Ilmajoki",
      "Isojoki",
      "Isokyrö",
      "Karijoki",
      "Kauhajoki",
      "Kauhava",
      "Kuortane",
      "Kurikka",
      "Lappajärvi",
      "Lapua",
      "Seinäjoki",
      "Soini",
      "Teuva",
      "Vimpeli",
      "Ähtäri",
    ],
  },
  {
    name: "Kela-taksi: Vaasan Ulataksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-34",
    group: 'Kela-taksi',
    phone: "0800 500 500",
    phoneUrl: 'tel:0800500500',
    specialty: 'fi',
    type: 'kela-taxi',
    municipalities: [
      "Kaskinen",
      "Korsnäs",
      "Kristiinankaupunki",
      "Kruunupyy",
      "Laihia",
      "Luoto",
      "Maalahti",
      "Mustasaari",
      "Närpiö",
      "Pedersören kunta",
      "Pietarsaari",
      "Uusikaarlepyy",
      "Vaasa",
      "Vöyri",
    ],
  },
  {
    name: "Kela-taksi ruotsiksi: Keskustaksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-35",
    group: 'Kela-taksi',
    phone: "0800 924 46",
    phoneUrl: 'tel:080092446',
    specialty: 'sv',
    type: 'kela-taxi',
    municipalities: [
      "Kaskinen",
      "Korsnäs",
      "Kristiinankaupunki",
      "Kruunupyy",
      "Laihia",
      "Luoto",
      "Maalahti",
      "Mustasaari",
      "Närpiö",
      "Pedersören kunta",
      "Pietarsaari",
      "Uusikaarlepyy",
      "Vaasa",
      "Vöyri",
    ],
  },
  {
    name: "Kela-taksi ruotsiksi: Menevä Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-36",
    group: 'Kela-taksi',
    phone: "0800 021 82",
    phoneUrl: 'tel:080002182',
    specialty: 'sv',
    type: 'kela-taxi',
    municipalities: [
      "Aura",
      "Kaarina",
      "Kemiönsaari",
      "Koski Tl",
      "Kustavi",
      "Laitila",
      "Lieto",
      "Loimaa",
      "Marttila",
      "Masku",
      "Mynämäki",
      "Naantali",
      "Nousiainen",
      "Oripää",
      "Paimio",
      "Parainen",
      "Pyhäranta",
      "Pöytyä",
      "Raisio",
      "Rusko",
      "Salo",
      "Sauvo",
      "Somero",
      "Taivassalo",
      "Turku",
      "Uusikaupunki",
      "Vehmaa",
    ],
  },
  {
    name: "Kela-taksi ruotsiksi: Pohjois-Suomen Taksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-37",
    group: 'Kela-taksi',
    phone: "0800 933 11",
    phoneUrl: 'tel:080093311',
    specialty: 'sv',
    type: 'kela-taxi',
    municipalities: [
      "Alavieska",
      "Haapajärvi",
      "Haapavesi",
      "Hailuoto",
      "Halsua",
      "Ii",
      "Kalajoki",
      "Kannus",
      "Kaustinen",
      "Kempele",
      "Kokkola",
      "Kuusamo",
      "Kärsämäki",
      "Lestijärvi",
      "Liminka",
      "Lumijoki",
      "Merijärvi",
      "Muhos",
      "Nivala",
      "Oulainen",
      "Oulu",
      "Perho",
      "Pudasjärvi",
      "Pyhäjoki",
      "Pyhäjärvi",
      "Pyhäntä",
      "Raahe",
      "Reisjärvi",
      "Sievi",
      "Siikajoki",
      "Siikalatva",
      "Taivalkoski",
      "Toholampi",
      "Tyrnävä",
      "Utajärvi",
      "Vaala",
      "Veteli",
      "Ylivieska",
    ],
  },
  {
    name: "Kela-taksi ruotsiksi: Suomen Lähilogistiikka Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-38",
    group: 'Kela-taksi',
    phone: "0800 051 51",
    phoneUrl: 'tel:080005151',
    specialty: 'sv',
    type: 'kela-taxi',
    municipalities: [
      "Askola",
      "Espoo",
      "Hanko",
      "Helsinki",
      "Hyvinkää",
      "Inkoo",
      "Järvenpää",
      "Karkkila",
      "Kauniainen",
      "Kerava",
      "Kirkkonummi",
      "Lapinjärvi",
      "Lohja",
      "Loviisa",
      "Myrskylä",
      "Mäntsälä",
      "Nurmijärvi",
      "Pornainen",
      "Porvoo",
      "Pukkila",
      "Raasepori",
      "Sipoo",
      "Siuntio",
      "Tuusula",
      "Vantaa",
      "Vihti",
    ],
  },
  {
    name: "Kela-taksi ruotsiksi: Taksi Helsinki Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-39",
    group: 'Kela-taksi',
    phone: "0800 414 601",
    phoneUrl: 'tel:0800414601',
    specialty: 'sv',
    type: 'kela-taxi',
    municipalities: [
      "Askola",
      "Espoo",
      "Hanko",
      "Helsinki",
      "Hyvinkää",
      "Inkoo",
      "Järvenpää",
      "Karkkila",
      "Kauniainen",
      "Kerava",
      "Kirkkonummi",
      "Lapinjärvi",
      "Lohja",
      "Loviisa",
      "Myrskylä",
      "Mäntsälä",
      "Nurmijärvi",
      "Pornainen",
      "Porvoo",
      "Pukkila",
      "Raasepori",
      "Sipoo",
      "Siuntio",
      "Tuusula",
      "Vantaa",
      "Vihti",
    ],
  },
  {
    name: "Kela-taksi ruotsiksi: Taksi Helsinki Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-40",
    group: 'Kela-taksi',
    phone: "0800 414 604",
    phoneUrl: 'tel:0800414604',
    specialty: 'sv',
    type: 'kela-taxi',
    municipalities: [
      "Aura",
      "Kaarina",
      "Kemiönsaari",
      "Koski Tl",
      "Kustavi",
      "Laitila",
      "Lieto",
      "Loimaa",
      "Marttila",
      "Masku",
      "Mynämäki",
      "Naantali",
      "Nousiainen",
      "Oripää",
      "Paimio",
      "Parainen",
      "Pyhäranta",
      "Pöytyä",
      "Raisio",
      "Rusko",
      "Salo",
      "Sauvo",
      "Somero",
      "Taivassalo",
      "Turku",
      "Uusikaupunki",
      "Vehmaa",
    ],
  },
  {
    name: "Kela-taksi ruotsiksi: Tampereen Aluetaksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-41",
    group: 'Kela-taksi',
    phone: "0800 415 730",
    phoneUrl: 'tel:0800415730',
    specialty: 'sv',
    type: 'kela-taxi',
    municipalities: [
      "Alavieska",
      "Haapajärvi",
      "Haapavesi",
      "Hailuoto",
      "Halsua",
      "Ii",
      "Kalajoki",
      "Kannus",
      "Kaustinen",
      "Kempele",
      "Kokkola",
      "Kuusamo",
      "Kärsämäki",
      "Lestijärvi",
      "Liminka",
      "Lumijoki",
      "Merijärvi",
      "Muhos",
      "Nivala",
      "Oulainen",
      "Oulu",
      "Perho",
      "Pudasjärvi",
      "Pyhäjoki",
      "Pyhäjärvi",
      "Pyhäntä",
      "Raahe",
      "Reisjärvi",
      "Sievi",
      "Siikajoki",
      "Siikalatva",
      "Taivalkoski",
      "Toholampi",
      "Tyrnävä",
      "Utajärvi",
      "Vaala",
      "Veteli",
      "Ylivieska",
    ],
  },
  {
    name: "Kela-taksi ruotsiksi: Vaasan Ulataksi Oy",
    url: "https://www.kela.fi/documents/20124/410312/Kela-taksin-tilausnumerot-kunnittain.pdf/dcccfb7a-4baa-edd4-64c8-0e4280360d38?t=1638453233868#kela-taksi-42",
    group: 'Kela-taksi',
    phone: "0800 500 600",
    phoneUrl: 'tel:0800500600',
    specialty: 'sv',
    type: 'kela-taxi',
    municipalities: [
      "Kaskinen",
      "Korsnäs",
      "Kristiinankaupunki",
      "Kruunupyy",
      "Laihia",
      "Luoto",
      "Maalahti",
      "Mustasaari",
      "Närpiö",
      "Pedersören kunta",
      "Pietarsaari",
      "Uusikaarlepyy",
      "Vaasa",
      "Vöyri",
    ],
  },
];
