// Generated by scripts/update-links.mjs.
export const LOCAL_LINK_STATS = {
  municipalities: 308,
  wellbeingAreas: 23,
  municipalityServicePages: 9,
  localTransport: 9,
  localLibraries: 8,
  localNewspapers: 120,
} as const;
