import type { RegionalProvider } from './communityLinks';

export const LOCAL_SPORTS_CLUBS: RegionalProvider[] = [
  { name: 'KP-75', url: 'https://www.kp-75.fi/', group: 'Kerava', municipality: 'Kerava', specialty: 'Jalkapallo' },
  { name: 'Keravan Urheilijat', url: 'https://keravanurheilijat.fi/', group: 'Kerava', municipality: 'Kerava', specialty: 'Urheiluseura' },
  { name: 'Keski-Uudenmaan Yleisurheilu', url: 'https://www.kuy.fi/', group: 'Keski-Uusimaa', municipalities: ['Järvenpää', 'Kerava', 'Tuusula'], specialty: 'Yleisurheilu' },
  { name: 'PK Keski-Uusimaa', url: 'https://pkku.fi/', group: 'Keski-Uusimaa', municipalities: ['Kerava', 'Tuusula'], specialty: 'Jalkapallo' },
  { name: 'HJK', url: 'https://hjk.fi/', group: 'Helsinki', municipality: 'Helsinki', specialty: 'Jalkapallo' },
  { name: 'HIFK Fotboll', url: 'https://hifkfotboll.fi/', group: 'Helsinki', municipality: 'Helsinki', specialty: 'Jalkapallo' },
  { name: 'Tapiolan Honka', url: 'https://www.tapiolanhonka.fi/', group: 'Espoo', municipality: 'Espoo', specialty: 'Koripallo' },
  { name: 'Esport Oilers', url: 'https://www.esportoilers.fi/', group: 'Espoo', municipality: 'Espoo', specialty: 'Salibandy' },
  { name: 'Vantaan Jalkapalloseura', url: 'https://vjs.fi/', group: 'Vantaa', municipality: 'Vantaa', specialty: 'Jalkapallo' },
  { name: 'Ilves', url: 'https://ilves.fi/', group: 'Tampere', municipality: 'Tampere', specialty: 'Urheiluseura' },
  { name: 'Tappara', url: 'https://www.tappara.fi/', group: 'Tampere', municipality: 'Tampere', specialty: 'Jääkiekko' },
  { name: 'Tampereen Pyrintö', url: 'https://pyrinto.fi/', group: 'Tampere', municipality: 'Tampere', specialty: 'Urheiluseura' },
  { name: 'TPS', url: 'https://fc.tps.fi/', group: 'Turku', municipality: 'Turku', specialty: 'Jalkapallo' },
  { name: 'Turun Urheiluliitto', url: 'https://www.turunurheiluliitto.fi/', group: 'Turku', municipality: 'Turku', specialty: 'Yleisurheilu' },
  { name: 'Oulun Kärpät', url: 'https://karpat.fi/', group: 'Oulu', municipality: 'Oulu', specialty: 'Jääkiekko' },
  { name: 'AC Oulu', url: 'https://acoulu.fi/', group: 'Oulu', municipality: 'Oulu', specialty: 'Jalkapallo' },
  { name: 'Oulun Pyrintö', url: 'https://oulunpyrinto.fi/', group: 'Oulu', municipality: 'Oulu', specialty: 'Urheiluseura' },
  { name: 'JYP', url: 'https://www.jypliiga.fi/', group: 'Jyväskylä', municipality: 'Jyväskylä', specialty: 'Jääkiekko' },
  { name: 'Jyväskylän Kenttäurheilijat', url: 'https://www.jku.fi/', group: 'Jyväskylä', municipality: 'Jyväskylä', specialty: 'Yleisurheilu' },
  { name: 'KuPS', url: 'https://kups.fi/', group: 'Kuopio', municipality: 'Kuopio', specialty: 'Jalkapallo' },
  { name: 'KalPa', url: 'https://kalpa.fi/', group: 'Kuopio', municipality: 'Kuopio', specialty: 'Jääkiekko' },
  { name: 'FC Lahti', url: 'https://fclahti.fi/', group: 'Lahti', municipality: 'Lahti', specialty: 'Jalkapallo' },
  { name: 'Lahden Ahkera', url: 'https://www.lahdenahkera.fi/', group: 'Lahti', municipality: 'Lahti', specialty: 'Yleisurheilu' },
  { name: 'Porin Ässät', url: 'https://assat.com/', group: 'Pori', municipality: 'Pori', specialty: 'Jääkiekko' },
  { name: 'Pesäkarhut', url: 'https://pesakarhut.fi/', group: 'Pori', municipality: 'Pori', specialty: 'Pesäpallo' },
  { name: 'Joensuun Kataja', url: 'https://www.joensuunkataja.fi/', group: 'Joensuu', municipality: 'Joensuu', specialty: 'Urheiluseura' },
  { name: 'Joensuun Maila', url: 'https://joensuunmaila.fi/', group: 'Joensuu', municipality: 'Joensuu', specialty: 'Pesäpallo' },
  { name: 'KooKoo', url: 'https://kookoo.fi/', group: 'Kouvola', municipality: 'Kouvola', specialty: 'Jääkiekko' },
  { name: 'Kouvolan Pallonlyöjät', url: 'https://kouvolanpallonlyojat.fi/', group: 'Kouvola', municipality: 'Kouvola', specialty: 'Pesäpallo' },
  { name: 'SaiPa', url: 'https://saipa.fi/', group: 'Lappeenranta', municipality: 'Lappeenranta', specialty: 'Jääkiekko' },
  { name: 'Vaasan Sport', url: 'https://vaasansport.fi/', group: 'Vaasa', municipality: 'Vaasa', specialty: 'Jääkiekko' },
  { name: 'Vaasan Palloseura', url: 'https://www.vepsu.fi/', group: 'Vaasa', municipality: 'Vaasa', specialty: 'Jalkapallo' },
  { name: 'RoPS', url: 'https://rops.fi/', group: 'Rovaniemi', municipality: 'Rovaniemi', specialty: 'Jalkapallo' },
  { name: 'SJK', url: 'https://sjk.fi/', group: 'Seinäjoki', municipality: 'Seinäjoki', specialty: 'Jalkapallo' },
  { name: 'Mikkelin Palloilijat', url: 'https://mikkelinpalloilijat.fi/', group: 'Mikkeli', municipality: 'Mikkeli', specialty: 'Jalkapallo' },
  { name: 'FC KTP', url: 'https://fcktp.fi/', group: 'Kotka', municipality: 'Kotka', specialty: 'Jalkapallo' },
  { name: 'KTP-Basket', url: 'https://www.ktpbasket.fi/', group: 'Kotka', municipality: 'Kotka', specialty: 'Koripallo' },
  { name: 'Rauman Lukko', url: 'https://www.raumanlukko.fi/', group: 'Rauma', municipality: 'Rauma', specialty: 'Jääkiekko' },
  { name: 'HPK', url: 'https://hpk.fi/', group: 'Hämeenlinna', municipality: 'Hämeenlinna', specialty: 'Jääkiekko' },
  { name: 'Kokkolan Pallo-Veikot', url: 'https://kpv.fi/', group: 'Kokkola', municipality: 'Kokkola', specialty: 'Jalkapallo' },
  { name: 'LP Viesti', url: 'https://lpviesti.fi/', group: 'Salo', municipality: 'Salo', specialty: 'Lentopallo' },
  { name: 'Hyvinkään Tahko', url: 'https://www.hyvinkaantahko.fi/', group: 'Hyvinkää', municipality: 'Hyvinkää', specialty: 'Pesäpallo' },
  { name: 'Riihimäen Cocks', url: 'https://cocks.fi/', group: 'Riihimäki', municipality: 'Riihimäki', specialty: 'Käsipallo' },
  { name: 'SaPKo', url: 'https://www.sapko.fi/', group: 'Savonlinna', municipality: 'Savonlinna', specialty: 'Jääkiekko' },
  { name: 'Kajaanin Haka', url: 'https://www.kajaaninhaka.fi/', group: 'Kajaani', municipality: 'Kajaani', specialty: 'Jalkapallo' }
];
