// Generated by scripts/update-municipality-website-locales.mjs on 2026-05-05.
// Keys match normalized Finnish municipality names in municipalityWebsites.ts.
import type { LanguageCode } from './i18n';

export const MUNICIPALITY_WEBSITE_LANGUAGE_URLS: Record<string, Partial<Record<LanguageCode, string>>> = {
  "akaa": {
    en: "https://akaa.fi/en/"
  },
  "alavieska": {
    en: "https://www.alavieska.fi/english"
  },
  "brändö": {
    en: "https://www.brando.ax/english/",
    sv: "https://www.brando.ax/"
  },
  "eckerö": {
    sv: "https://www.eckero.ax/"
  },
  "enontekiö": {
    en: "https://enontekio.fi/en",
    se: "https://enontekio.fi/se"
  },
  "espoo": {
    en: "https://www.espoo.fi/en",
    sv: "https://www.espoo.fi/sv"
  },
  "eura": {
    en: "https://www.eura.fi/in-english/"
  },
  "finström": {
    sv: "https://www.finstrom.ax/"
  },
  "forssa": {
    en: "https://www.forssa.fi/in-english/",
    sv: "https://www.forssa.fi/pa-svenska/"
  },
  "föglö": {
    sv: "https://www.foglo.ax/"
  },
  "geta": {
    sv: "https://www.geta.ax/"
  },
  "hammarland": {
    sv: "https://www.hammarland.ax/",
    uk: "https://www.hammarland.ax/kommunen/ukraina-information"
  },
  "hanko": {
    sv: "https://hanko.fi/sv/"
  },
  "hattula": {
    en: "https://hattula.fi/briefly-in-english/"
  },
  "heinola": {
    en: "https://www.heinola.fi/in_english/"
  },
  "heinävesi": {
    en: "https://www.heinavesi.fi/en/in-english/"
  },
  "helsinki": {
    en: "https://www.hel.fi/en/frontpage",
    et: "https://www.hel.fi/et",
    ru: "https://www.hel.fi/ru",
    sv: "https://www.hel.fi/sv/huvudsida",
    uk: "https://www.hel.fi/uk"
  },
  "hirvensalmi": {
    en: "https://www.hirvensalmi.fi/english/"
  },
  "hollola": {
    en: "https://hollola.fi/"
  },
  "humppila": {
    en: "https://www.humppila.fi/english/"
  },
  "hyrynsalmi": {
    en: "https://hyrynsalmi.fi/en/"
  },
  "hyvinkää": {
    en: "https://www.hyvinkaa.fi/in-english/",
    sv: "https://www.hyvinkaa.fi/pa-svenska/"
  },
  "hämeenlinna": {
    en: "https://www.hameenlinna.fi/en/",
    sv: "https://www.hameenlinna.fi/sv/"
  },
  "ilmajoki": {
    en: "http://ilmajoki.fi/ilmajoki-in-english/"
  },
  "inari": {
    en: "https://www.inari.fi/en/home-page.html",
    ru: "https://www.inari.fi/ru/glavnaja-stranica.html",
    se: "https://www.inari.fi/se/se/koltansaameetusivu-2018.html",
    sv: "https://www.inari.fi/sv/forstasida.html"
  },
  "inkoo": {
    sv: "https://www.inga.fi/sv/?s="
  },
  "isojoki": {
    en: "https://isojoki.fi/english/"
  },
  "janakkala": {
    en: "https://www.janakkala.fi/en/"
  },
  "joensuu": {
    en: "https://www.joensuu.fi/en/"
  },
  "jokioinen": {
    en: "https://www.jokioinen.fi/in-english/"
  },
  "jomala": {
    sv: "https://www.jomala.ax/"
  },
  "joutsa": {
    en: "https://www.joutsa.fi/in-english/"
  },
  "juuka": {
    en: "https://www.juuka.fi/en/web/english",
    ru: "https://www.juuka.fi/ru/web/russian"
  },
  "juupajoki": {
    en: "https://juupajoki.fi/en/"
  },
  "juva": {
    en: "https://www.juva.fi/en"
  },
  "jyväskylä": {
    en: "https://www.jyvaskyla.fi/en"
  },
  "jämijärvi": {
    en: "https://jamijarvi.fi/en/etusivu-english/"
  },
  "kajaani": {
    en: "https://kajaani.fi/en/home/"
  },
  "kalajoki": {
    en: "https://www.kalajoki.fi/en"
  },
  "kangasniemi": {
    en: "https://www.kangasniemi.fi/en/home/",
    ru: "https://www.kangasniemi.fi/ru/%d0%b4%d0%be%d0%bc%d0%b0%d1%88%d0%bd%d1%8f%d1%8f-%d1%81%d1%82%d1%80%d0%b0%d0%bd%d0%b8%d1%86%d0%b0/",
    sv: "https://www.kangasniemi.fi/sv/framsidan/"
  },
  "kannonkoski": {
    en: "https://kannonkoski.fi/kannonkoski-in-english"
  },
  "karijoki": {
    en: "https://karijoki.fi/english/"
  },
  "kaskinen": {
    sv: "https://kaskinen.fi/sv"
  },
  "kauhava": {
    en: "https://kauhava.fi/en/"
  },
  "kauniainen": {
    sv: "https://www.kauniainen.fi/sv/"
  },
  "keitele": {
    en: "https://keitele.fi/en/front-page/"
  },
  "kemi": {
    en: "https://www.kemi.fi/en/",
    sv: "https://www.kemi.fi/sv/"
  },
  "kemijärvi": {
    en: "https://kemijarvi.fi/en/"
  },
  "kemiönsaari": {
    en: "https://en.kimitoon.fi/",
    sv: "https://www.kimitoon.fi/"
  },
  "keuruu": {
    en: "https://keuruu.fi/en/"
  },
  "kirkkonummi": {
    sv: "https://kyrkslatt.fi/"
  },
  "kitee": {
    en: "https://www.kitee.fi/en/web/eng",
    ru: "https://www.kitee.fi/ru/web/rus"
  },
  "kittilä": {
    en: "https://kittila.fi/en"
  },
  "kiuruvesi": {
    en: "https://kiuruvesi.fi/in-english/",
    et: "https://kiuruvesi.fi/eesti-keeles/",
    sv: "https://kiuruvesi.fi/svenska/"
  },
  "kivijärvi": {
    en: "https://www.kivijarvi.fi/english"
  },
  "kokkola": {
    en: "https://www.kokkola.fi/en/",
    sv: "https://www.kokkola.fi/sv/"
  },
  "korsnäs": {
    sv: "https://www.korsnas.fi/"
  },
  "kotka": {
    en: "https://www.kotka.fi/en/",
    ru: "https://www.kotka.fi/ru/"
  },
  "kouvola": {
    en: "https://www.kouvola.fi/en/",
    ru: "https://www.kouvola.fi/ru/"
  },
  "kristiinankaupunki": {
    en: "https://www.kristinestad.fi/start/",
    sv: "https://www.kristinestad.fi/"
  },
  "kruunupyy": {
    sv: "https://www.kronoby.fi/sv"
  },
  "kumlinge": {
    en: "https://www.kumlinge.ax/en/",
    sv: "https://www.kumlinge.ax/"
  },
  "kuopio": {
    en: "https://www.kuopio.fi/en/frontpage/",
    ru: "https://www.kuopio.fi/ru/%d0%b3%d0%bb%d0%b0%d0%b2%d0%bd%d0%b0%d1%8f-%d1%81%d1%82%d1%80%d0%b0%d0%bd%d0%b8%d1%86%d0%b0-%d1%81%d0%b0%d0%b9%d1%82%d0%b0/"
  },
  "kuortane": {
    en: "https://kuortane.fi/en/"
  },
  "kustavi": {
    en: "https://kustavi.fi/en/"
  },
  "kökar": {
    sv: "https://www.kokar.ax/"
  },
  "lahti": {
    en: "https://www.lahti.fi/en/"
  },
  "laitila": {
    en: "https://www.laitila.fi/en/",
    uk: "https://www.laitila.fi/uk/"
  },
  "lapinjärvi": {
    sv: "https://lapinjarvi.fi/sv/"
  },
  "lapinlahti": {
    en: "https://lapinlahti.fi/visit-lapinlahti-en"
  },
  "lapua": {
    en: "https://lapua.fi/en/",
    sv: "https://lapua.fi/sv/"
  },
  "laukaa": {
    en: "https://www.laukaa.fi/en/",
    sv: "https://www.laukaa.fi/sv/"
  },
  "lemi": {
    en: "https://lemi.fi/in-english/"
  },
  "lemland": {
    sv: "https://www.lemland.ax/"
  },
  "lempäälä": {
    en: "https://www.lempaala.fi/briefly-in-english/"
  },
  "leppävirta": {
    en: "https://leppavirta.fi/in-english/"
  },
  "lestijärvi": {
    en: "https://lestijarvi.fi/en/home-2/"
  },
  "lieto": {
    sv: "https://lieto.fi/sv/framsida"
  },
  "lohja": {
    sv: "https://www.lohja.fi/sv/"
  },
  "loimaa": {
    en: "https://www.loimaa.fi/en/"
  },
  "loviisa": {
    en: "https://www.loviisa.fi/en/",
    sv: "https://www.loviisa.fi/sv/"
  },
  "lumparland": {
    sv: "https://www.lumparland.ax/"
  },
  "luoto": {
    en: "https://larsmo.fi/en/frontpage/",
    sv: "https://larsmo.fi/"
  },
  "maalahti": {
    en: "https://www.malax.fi/en/",
    sv: "https://www.malax.fi/"
  },
  "maarianhamina": {
    sv: "https://www.mariehamn.ax/"
  },
  "mikkeli": {
    en: "https://mikkeli.fi/en/",
    sv: "https://mikkeli.fi/sv/"
  },
  "muonio": {
    en: "https://www.muonio.fi/en/home.html"
  },
  "mustasaari": {
    en: "https://en.korsholm.fi/",
    sv: "https://korsholm.fi/"
  },
  "muurame": {
    uk: "https://www.muurame.fi/palvelut/ukraina-1/"
  },
  "mynämäki": {
    en: "https://www.mynamaki.fi/english/"
  },
  "myrskylä": {
    sv: "https://myrskyla.fi/sv/"
  },
  "mänttä-vilppula": {
    en: "https://manttavilppula.fi/in-english"
  },
  "naantali": {
    en: "https://www.naantali.fi/en",
    sv: "https://www.naantali.fi/sv"
  },
  "nurmijärvi": {
    en: "https://www.nurmijarvi.fi/nurmijarvi-in-english/",
    sv: "https://www.nurmijarvi.fi/pa-svenska/"
  },
  "närpiö": {
    sv: "https://www.narpes.fi/"
  },
  "oripää": {
    en: "https://oripaa.fi/in-english/"
  },
  "orivesi": {
    en: "https://orivesi.fi/en/front-page/"
  },
  "oulainen": {
    en: "https://www.oulainen.fi/en",
    ru: "https://www.oulainen.fi/ru"
  },
  "oulu": {
    en: "https://www.ouka.fi/en/etusivu",
    sv: "https://www.ouka.fi/sv/framsida"
  },
  "outokumpu": {
    en: "https://www.outokummunkaupunki.fi/in-english/"
  },
  "paltamo": {
    en: "https://www.paltamo.fi/en/home.html"
  },
  "parainen": {
    en: "https://www.pargas.fi/en/web/pargas-eng",
    sv: "https://www.pargas.fi/sv",
    uk: "https://www.pargas.fi/sv/ukraina-info"
  },
  "parkano": {
    en: "https://parkano.fi/en/"
  },
  "pedersören kunta": {
    en: "https://www.pedersore.fi/en/",
    sv: "https://www.pedersore.fi/sv/soek/"
  },
  "pelkosenniemi": {
    en: "https://pelkosenniemi.fi/en/"
  },
  "pello": {
    en: "https://www.pello.fi/en/home.html"
  },
  "pieksämäki": {
    ru: "https://www.pieksamaki.fi/"
  },
  "pielavesi": {
    en: "https://pielavesi.fi/en/"
  },
  "pietarsaari": {
    en: "https://en.jakobstad.fi/",
    sv: "https://jakobstad.fi/"
  },
  "pirkkala": {
    en: "https://www.pirkkala.fi/en/front-page/"
  },
  "pori": {
    en: "https://www.pori.fi/en/"
  },
  "porvoo": {
    en: "https://www.porvoo.fi/en/",
    sv: "https://www.porvoo.fi/sv/"
  },
  "posio": {
    en: "https://www.posio.fi/"
  },
  "pukkila": {
    en: "https://www.pukkila.fi/in-english/"
  },
  "puumala": {
    en: "https://puumala.fi/en/home/",
    ru: "https://puumala.fi/ru/%d0%b3%d0%bb%d0%b0%d0%b2%d0%bd%d0%b0%d1%8f/"
  },
  "pyhtää": {
    en: "https://pyhtaa.fi/en",
    sv: "https://pyhtaa.fi/sv"
  },
  "pyhäjoki": {
    en: "https://www.pyhajoki.fi/en",
    sv: "https://www.pyhajoki.fi/sv"
  },
  "raahe": {
    en: "https://www.raahe.fi/en/node/295",
    ru: "https://www.raahe.fi/ru/node/295",
    sv: "https://www.raahe.fi/sv/node/295"
  },
  "raasepori": {
    sv: "https://www.raseborg.fi/skolor/karis-svenska-hogstadium/"
  },
  "raisio": {
    en: "https://raisio.fi/en"
  },
  "rantasalmi": {
    en: "https://www.rantasalmi.fi/en/"
  },
  "ranua": {
    en: "https://ranua.fi/en/"
  },
  "rauma": {
    en: "https://www.rauma.fi/en/"
  },
  "rautalampi": {
    en: "https://www.rautalampi.fi/english/"
  },
  "reisjärvi": {
    en: "https://www.reisjarvi.fi/contact-english"
  },
  "rovaniemi": {
    en: "https://international.rovaniemi.fi/"
  },
  "ruovesi": {
    en: "https://www.ruovesi.fi/tourists/"
  },
  "salla": {
    en: "https://www.salla.fi/en/"
  },
  "salo": {
    en: "https://salo.fi/en/",
    sv: "https://salo.fi/sv/"
  },
  "saltvik": {
    sv: "https://www.saltvik.ax/"
  },
  "sauvo": {
    en: "https://www.sauvo.fi/?lang=en",
    sv: "https://www.sauvo.fi/?lang=sv"
  },
  "savonlinna": {
    en: "https://www.savonlinna.fi/en/",
    ru: "https://www.savonlinna.fi/ru/",
    sv: "https://www.savonlinna.fi/sv/"
  },
  "seinäjoki": {
    en: "https://www.seinajoki.fi/en/",
    sv: "https://www.seinajoki.fi/sv/"
  },
  "siikainen": {
    en: "https://siikainen.fi/in-english"
  },
  "siikalatva": {
    en: "https://siikalatva.fi/en/frontpage/"
  },
  "siilinjärvi": {
    en: "https://siilinjarvi.fi/en/"
  },
  "sipoo": {
    en: "https://www.sipoo.fi/en/",
    sv: "https://www.sipoo.fi/sv/"
  },
  "siuntio": {
    sv: "https://www.siuntio.fi/sv/"
  },
  "sodankylä": {
    en: "https://www.sodankyla.fi/en/"
  },
  "somero": {
    en: "https://www.somero.fi/in-english/"
  },
  "sotkamo": {
    en: "https://www.sotkamo.fi/en/"
  },
  "sottunga": {
    sv: "https://www.sottunga.ax/"
  },
  "sulkava": {
    en: "https://sulkava.fi/en/",
    ru: "https://sulkava.fi/ru/"
  },
  "sund": {
    sv: "https://www.sund.ax/"
  },
  "suomussalmi": {
    en: "https://suomussalmi.fi/en"
  },
  "suonenjoki": {
    en: "https://suonenjoki.fi/en/"
  },
  "sysmä": {
    sv: "https://sysma.fi/blanketter-pa-svenska/"
  },
  "säkylä": {
    en: "https://www.sakyla.fi/en/",
    sv: "https://www.sakyla.fi/sv/"
  },
  "taivalkoski": {
    en: "https://taivalkoski.fi/en/welcome/"
  },
  "tammela": {
    en: "https://www.tammela.fi/in-english"
  },
  "tampere": {
    en: "https://www.tampere.fi/en"
  },
  "tervo": {
    en: "https://www.tervo.fi/english",
    sv: "https://www.tervo.fi/svenska"
  },
  "tervola": {
    en: "https://tervola.fi/en/"
  },
  "tohmajärvi": {
    en: "https://www.tohmajarvi.fi/en/web/english",
    ru: "https://www.tohmajarvi.fi/ru/web/russia"
  },
  "toholampi": {
    en: "https://www.toholampi.fi/english/"
  },
  "toivakka": {
    en: "https://www.toivakka.fi/en/"
  },
  "tornio": {
    en: "https://www.tornio.fi/en/",
    sv: "https://www.tornio.fi/sv/"
  },
  "turku": {
    en: "https://www.turku.fi/en",
    sv: "https://www.turku.fi/sv"
  },
  "tuusniemi": {
    en: "https://www.tuusniemi.fi/english",
    sv: "https://www.tuusniemi.fi/svenska"
  },
  "tuusula": {
    en: "https://tuusula.fi/en/home/"
  },
  "tyrnävä": {
    en: "https://www.tyrnava.fi/en/home.html"
  },
  "utajärvi": {
    en: "https://www.utajarvi.fi/en/"
  },
  "utsjoki": {
    se: "https://www.utsjoki.fi/se/"
  },
  "uurainen": {
    en: "https://uurainen.fi/en/"
  },
  "uusikaarlepyy": {
    sv: "https://www.nykarleby.fi/"
  },
  "uusikaupunki": {
    en: "https://uusikaupunki.fi/en"
  },
  "vaala": {
    en: "https://www.vaala.fi/in-english/"
  },
  "vaasa": {
    en: "https://www.vaasa.fi/en/",
    sv: "https://www.vaasa.fi/sv/"
  },
  "vantaa": {
    en: "https://www.vantaa.fi/en",
    sv: "https://www.vantaa.fi/sv"
  },
  "varkaus": {
    en: "https://varkaus.fi/en",
    ru: "https://varkaus.fi/ru"
  },
  "virrat": {
    en: "https://www.virrat.fi/english"
  },
  "vårdö": {
    sv: "https://www.vardo.ax/"
  },
  "vöyri": {
    en: "https://www.vora.fi/en/",
    sv: "https://www.vora.fi/"
  },
  "ylivieska": {
    en: "https://www.ylivieska.fi/en/front-page/"
  },
  "ylöjärvi": {
    en: "https://www.ylojarvi.fi/in-english/",
    uk: "https://www.ylojarvi.fi/ukraina/"
  },
  "äänekoski": {
    en: "http://www.aanekoski.fi/en/",
    ru: "https://www.aanekoski.fi/ru/",
    sv: "https://www.aanekoski.fi/sv/",
    uk: "http://www.aanekoski.fi/uk/"
  }
};
